use_frameworks!

platform :ios, '9.0'

target 'YUtilCore_Example' do
  pod 'YUtilCore', :path => '../'

  target 'YUtilCore_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
